(
 ("default"   . ((user-emacs-directory . "~/.local/share/emacs")
    )
 )
 ("doom"      . ((user-emacs-directory . "/opt/emacs/doom-emacs")
                 (env . (("DOOMDIR" . "~/.config/emacs/doom")))
 ))
 ("spacemacs" . ((user-emacs-directory . "/opt/emacs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/config/emacs/spacemacs")))
 ))
 ("prelude"   . ((user-emacs-directory . "/opt/emacs/prelude")
                 (env . (("PRELUDEDIR" . "~/config/emacs/prelude")))
 ))
)
