#
# My POWERLEVEL9K Configuration
#

## Printing for debugging purposes if session is interactive
[[ -o interactive ]] && echo "Sourced: \$ZDOTDIR/themes/pl9k/dievilz-original.pl9k.zsh"


semifondo="000"
fondo="008"
cleaar="235"

POWERLEVEL9K_MODE="nerdfont-complete"
# POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
# POWERLEVEL9K_ALWAYS_SHOW_USER=true
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
# POWERLEVEL9K_SHORTEN_DELIMITER=""
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
# POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{cyan}/%F{blue}"
# POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND=""
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false #true
# POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
# POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
# POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
# POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="" #Mantener predeterminados
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}" #╭─
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} " #╰>

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    'root_indicator'  'context'  'dir_writable'  'dir'  'vcs'
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    'status'  'command_execution_time'  'background_jobs'  'battery'  'nvm'  'node_version'  'time' ) # 'ip'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="070"       #verde vcs chido
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="130"   #naranja feo vcs
POWERLEVEL9K_SHOW_CHANGESET=true
# POWERLEVEL9K_CHANGESET_HASH_LENGTH=12
# POWERLEVEL9K_VCS_HIDE_TAGS=false
# POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)

# POWERLEVEL9K_DIR_HOME_BACKGROUND="blue"
# POWERLEVEL9K_DIR_HOME_FOREGROUND="$fondo"
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="blue"
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$fondo"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="$fondo"
# POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="blue"
# POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$fondo"
# POWERLEVEL9K_DIR_ETC_BACKGROUND="blue"
# POWERLEVEL9K_DIR_ETC_FOREGROUND="$fondo"

# POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="grey3" #232 negro chido
# POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="226"   #amarillo chido

POWERLEVEL9K_STATUS_OK_BACKGROUND="grey19"    #236 gris darker
POWERLEVEL9K_STATUS_OK_FOREGROUND="040"       #verde chido
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="grey19" #236 gris darker
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="160"    #rojo chido
POWERLEVEL9K_STATUS_CROSS=false

POWERLEVEL9K_TIME_FORMAT="%t" # 09:32PM
#POWERLEVEL9K_TIME_BACKGROUND="grey46" #243 light gris oscuro
POWERLEVEL9K_TIME_FOREGROUND="$fondo"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="magenta"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$fondo"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="120" #verde backgrounds 2
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$fondo"
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true #Mostrar el contador siempre

POWERLEVEL9K_USER_DEFAULT_BACKGROUND="013" #morado
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="$fondo"
POWERLEVEL9K_USER_ROOT_BACKGROUND="$fondo"
POWERLEVEL9K_USER_ROOT_FOREGROUND="196" #rojo brillante
POWERLEVEL9K_USER_SUDO_BACKGROUND="$fondo"
POWERLEVEL9K_USER_SUDO_FOREGROUND="013" #morado

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="$fondo"

POWERLEVEL9K_HOST_LOCAL_BACKGROUND="cyan"
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="$fondo"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="magenta"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="$fondo"

POWERLEVEL9K_USER_ICON="\uF415"  #  user  predeterminado
POWERLEVEL9K_ROOT_ICON="\u26a1"  # rayito predeterminado
POWERLEVEL9K_SUDO_ICON="\uF09C" # candado desbloqueado
POWERLEVEL9K_HOST_ICON="\uF109 " #        predeterminados pero
 POWERLEVEL9K_SSH_ICON="\uF489 " # tienen un espacio posterior!

POWERLEVEL9K_IP_BACKGROUND="027" # azul medio oscuro
# POWERLEVEL9K_IP_FOREGROUND="$fondo"

# POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=""        # You are a normal user
# POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=""
# POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="$semifondo" # You are the root user
# POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="226"
# POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND=""           # You are using elevated rights
# POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=""
# POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=""         # You are SSH'ed into the machine
# POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=""
# POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=""    # You are sudo SSH'ed into the machine
# POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=""

# POWERLEVEL9K_SSH_BACKGROUND="221" # amarillo palido
# POWERLEVEL9K_SSH_FOREGROUND="$fondo"

# POWERLEVEL9K_NODE_VERSION_BACKGROUND="$fondo"
POWERLEVEL9K_NODE_VERSION_FOREGROUND="$fondo" #green / 022 verde
# POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_COLOR="002"
