#
# $ZDOTDIR/.zprofile  OR  ~/.zprofile
#

## Printing for debugging purposes if session is interactive
[[ -o interactive ]] && echo "Sourced: \$ZDOTDIR/.zprofile"

## This file doesn't contain the env vars we need, they are in ~/.profile.
## We need to verify if it has been somewhat sourced at this point, if not,
## source it right away,

if [ -z "$PROFILE_SOURCED" ];
then
	[ -r "$HOME/.profile" ] && . "$HOME/.profile"
fi
